apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
        app.kubernetes.io/name: pythonapp
        app.kubernetes.io/instance: pythonapp
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: hello-kubernetes-dapr
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/created-by: quickstart-user
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pythonapp"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: python
        image: ghcr.io/dapr/samples/hello-k8s-python:latest
